### ISSUE TITLE
Maybe a CompareSync Bug 

### ISSUE THREAD

**Issue by jackalsin** [shaneGirish/bcrypt-nodejs#68]
I encounter an issue when using CompareSync in model

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var bcrypt = require('bcrypt-nodejs');

// create a schema
var userSchema = new Schema({
  username: { type: String, required: true, unique: true },
  password: {type: String, required:true}
});

userSchema.methods.generateHash = function(password) {
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

// checking if password is valid
userSchema.methods.validPassword = function(password) {
  console.log("Normal call 7 " + password + "\t" + this.password); //todo debug line
  var result = bcrypt.compareSync(password, this.password);
  console.log("Normal 8" + result);
  return bcrypt.compareSync(password, this.password);
};

var Users = mongoose.model('Users', userSchema);
module.exports = Users;
```
The result is as follows
```
Normal call 7 password1234      password1234

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Function.EventEmitter.emit (events.js:74:15)
    at Query.<anonymous> (<project dir>/node_modules/mongoose/lib/model.js:3326:13)
    at <project dir>/node_modules/mongoose/node_modules/kareem/index.js:259:21
    at <project dir>/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at process._tickCallback (node.js:415:13)
```
As you can see, the program is normal before calling `compareSync`, and the Strings to compare are quite reasonable, and it throws an exception

**Comment by xgui3783** [comment]
I suspect the error occurs because compareSync(string,hash) takes string as the first argument and hash as the second. I suspect since hash should have considerably longer (and fixed) length, that's where the error occurs.

**Comment by jackalsin** [comment]
Thanks for the reply. After 4 days, I found it's a mongoose issue... Sorry for this. You can close now

[Related link](https://github.com/auth0/node-jsonwebtoken/issues/156#issuecomment-169035175)

**Comment by skulabs** [comment]
@jackalsin I read that ticket and couldn't figure out what the verdict was. From what I see, `bcrypt.hashSync` returns a string.

```
var query = {
	'users._id': user_id
};

var update = {
	'$set': {
		'users.$.password': str
	}
};
```

Why would this be an issue? Can you please explain what you did to resolve the issue?

**Comment by darmie** [comment]
I am having the same issue... how is hash not a string?

**Comment by jackalsin** [comment]
You can console.dir(the_obj_you_want_hash). Mongoose has changed the api. Dir the object.

**Comment by darmie** [comment]
Fixed. Thanks
